service: Nexum-server

useDotenv: true

plugins:
  - serverless-offline

provider:
  name: aws
  runtime: nodejs22.x
  profile: default
  stage: ${opt:stage, 'dev'}
  environment:
    PORT: ${ssm:/${self:provider.stage}/PORT}
    ENVIRONMENT_PREFIX: ${ssm:/${self:provider.stage}/ENVIRONMENT_PREFIX}
    MONGO_DB_URI: ${ssm:/${self:provider.stage}/MONGO_DB_URI}
    JWT_SECRET: ${ssm:/${self:provider.stage}/JWT_SECRET}
    JWT_EXPIRATION_TIME: ${ssm:/${self:provider.stage}/JWT_EXPIRATION_TIME}

custom:
  serverless-offline:
    httpPort: ${env:PORT}
    lambdaPort: 9002

functions:
  main:
    handler: dist/serverless.handler
    events:
      - http:
          method: ANY
          path: /
      - http:
          method: ANY
          path: '{proxy+}'
      - http:
          method: POST
          path: /auth/registration
      - http:
          method: POST
          path: /auth/login
