service: Nexum-server

useDotenv: true

plugins:
  - serverless-offline

provider:
  name: aws
  runtime: nodejs22.x
  profile: default
  environment:
    PORT: ${env:PORT}
    ENVIRONMENT_PREFIX: ${env:ENVIRONMENT_PREFIX}
    MONGO_DB_URI: ${env:MONGO_DB_URI}
    JWT_SECRET: ${env:JWT_SECRET}
    JWT_EXPIRATION_TIME: ${env:JWT_EXPIRATION_TIME}

custom:
  serverless-offline:
    httpPort: ${env:PORT}
    lambdaPort: 9002

functions:
  main:
    handler: dist/serverless.handler
    events:
      - http:
          method: ANY
          path: /
      - http:
          method: ANY
          path: '{proxy+}'
      - http:
          method: POST
          path: /auth/registration
      - http:
          method: POST
          path: /auth/login
