name: Deploy Rest API function

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Deployment Environment'
        required: true
        default: 'staging'
        type: choice
        options:
          - staging
          - prod

jobs:
  deploy_lambda:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '22'
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-north-1
      - name: Install dependencies
        env:
          CI: true
        run: |
          yarn install --frozen-lockfile
          yarn global add serverless

      - name: Authenticate Serverless
        env:
          SERVERLESS_ACCESS_KEY: ${{ secrets.SERVERLESS_ACCESS_KEY }}
        run: echo "Serverless authentication set"

      - name: Deploy with Serverless Framework
        env:
          SERVERLESS_ACCESS_KEY: ${{ secrets.SERVERLESS_ACCESS_KEY }}
        run: serverless deploy --stage ${{ github.event.inputs.environment }} --region eu-north-1

      - name: Build and Deploy
        run: |
          yarn build
          tsc
          zip -j deploy.zip ./dist/*
          aws lambda update-function-code --function-name=lambda-gh-action-${{ github.event.inputs.environment }} --zip-file=fileb://deploy.zip
