name: Deploy Rest API function

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Deployment Environment'
        required: true
        default: 'staging'
        type: choice
        options:
          - staging
          - prod

jobs:
  deploy_lambda:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '22'
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-north-1
      - name: Install dependencies
        env:
          CI: true
        run: |
          yarn install --frozen-lockfile
          yarn global add serverless

      - name: Authenticate Serverless
        env:
          SERVERLESS_ACCESS_KEY: ${{ secrets.SERVERLESS_ACCESS_KEY }}
        run: echo "Serverless authentication set"

      - name: Unset AWS Profile
        run: |
          echo "Unsetting AWS_PROFILE to prevent conflicts"
          unset AWS_PROFILE
          echo "AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}" >> $GITHUB_ENV
          echo "AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}" >> $GITHUB_ENV
          echo "AWS_REGION=eu-north-1" >> $GITHUB_ENV
          export AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}
          export AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}
          export AWS_DEFAULT_REGION=eu-north-1

      - name: Check IAM Permissions for SSM
        run: |
          echo "Checking SSM access..."
          aws ssm get-parameter --name "/staging/PORT" --region eu-north-1

      - name: Debug AWS Credentials
        run: aws sts get-caller-identity

      - name: Check if AWS Secrets Exist
        run: |
          echo "AWS_ACCESS_KEY_ID Length: ${#AWS_ACCESS_KEY_ID}"
          echo "AWS_SECRET_ACCESS_KEY Length: ${#AWS_SECRET_ACCESS_KEY}"

      - name: Deploy with Serverless Framework
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: eu-north-1
          AWS_DEFAULT_REGION: eu-north-1
          SERVERLESS_ACCESS_KEY: ${{ secrets.SERVERLESS_ACCESS_KEY }}
        run:
          serverless config credentials --provider aws --key $AWS_ACCESS_KEY_ID --secret $AWS_SECRET_ACCESS_KEY
          serverless deploy --stage ${{ github.event.inputs.environment }} --region eu-north-1

      - name: Build and Deploy
        run: |
          yarn build
          tsc
          zip -j deploy.zip ./dist/*
          aws lambda update-function-code --function-name=lambda-gh-action-${{ github.event.inputs.environment }} --zip-file=fileb://deploy.zip
