name: Deploy Rest API function

on:
  workflow_dispatch:

jobs:
  deploy_lambda:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '22'
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-north-1
      - name: yarn install
        env:
          CI: true
        run: |
          yarn install --frozen-lockfile

      - name: Install Serverless Framework
        run: yarn global add serverless

      - name: Deploy with Serverless Framework
        run: serverless deploy --stage prod --region eu-north-1

      - name: Authenticate Serverless
        run: serverless login --org nexumserver || echo "Skipping interactive login"

      - name: Build and Deploy
        run: |
          yarn build
          tsc
          zip -j deploy.zip ./dist/*
          aws lambda update-function-code --function-name=lambda-gh-action --zip-file=fileb://deploy.zip